"use client";
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { createSupabaseClientInstance } from '@/lib/supabase';
function id(prefix: string) { return crypto.randomUUID?.() ?? `${prefix}-${Date.now()}`; }
export function ClientRequestPage({ projectId, request, messages, references, displayName }: { projectId: string; request: { id: string; title: string; brief: string; status: string }; messages: Array<{ id: string; authorName: string; body: string }>; references: Array<{ id: string; title: string | null; url: string | null; note: string | null }>; displayName: string }) {
  const router = useRouter(); const [reply, setReply] = useState(''); const [message, setMessage] = useState<string | null>(null); const [editing, setEditing] = useState(false); const [title, setTitle] = useState(request.title); const [brief, setBrief] = useState(request.brief); const amendable = request.status === 'new' && !messages.length;
  const sendReply = async () => { const client = createSupabaseClientInstance(); if (!client || !reply.trim()) return; const { error } = await client.from('project_request_messages').insert({ id: id('request-message'), request_id: request.id, author_role: 'client', author_name: displayName || 'Client', body: reply.trim() }); if (error) setMessage(error.message); else { setReply(''); router.refresh(); } };
  const amend = async () => { const client = createSupabaseClientInstance(); if (!client) return; const { error } = await client.rpc('edit_authenticated_project_request', { p_request_id: request.id, p_title: title, p_brief: brief }); if (error) setMessage(error.message); else { setEditing(false); router.refresh(); } };
  const withdraw = async () => { const client = createSupabaseClientInstance(); if (!client || !window.confirm('Withdraw this Request?')) return; const { error } = await client.rpc('withdraw_authenticated_project_request', { p_request_id: request.id }); if (error) setMessage(error.message); else router.push(`/client/projects/${projectId}`); };
  return <main className="min-h-screen bg-canvas px-4 py-6 text-text lg:px-8"><header className="border-b border-border pb-5"><Link href={`/client/projects/${projectId}`} className="text-sm font-semibold text-text-muted">← Project</Link><p className="mt-4 text-xs font-semibold uppercase tracking-[0.2em] text-text-subtle">Request</p>{editing ? <form onSubmit={(event) => { event.preventDefault(); void amend(); }} className="mt-3 max-w-3xl"><input value={title} onChange={(event) => setTitle(event.target.value)} className="w-full rounded-md border border-border px-3 py-2 text-xl font-semibold"/><textarea value={brief} onChange={(event) => setBrief(event.target.value)} className="mt-3 min-h-28 w-full rounded-md border border-border px-3 py-2"/><button className="mt-3 rounded-md bg-brand px-3 py-2 text-sm font-semibold text-white">Save changes</button></form> : <><h1 className="mt-2 text-3xl font-semibold">{request.title}</h1><p className="mt-4 max-w-3xl whitespace-pre-wrap text-sm leading-6 text-text-muted">{request.brief}</p>{amendable ? <div className="mt-4 flex gap-2"><button onClick={() => setEditing(true)} className="rounded-md border border-border px-3 py-2 text-sm font-semibold">Edit</button><button onClick={() => void withdraw()} className="rounded-md border border-border px-3 py-2 text-sm font-semibold text-text-muted">Withdraw</button></div> : null}</>}</header>{message ? <p className="mt-4 text-sm text-text-muted">{message}</p> : null}<section className="mt-6 rounded-lg border border-border bg-surface p-4"><h2 className="font-semibold">Discussion</h2><div className="mt-4 space-y-3">{messages.map((item) => <article key={item.id} className="rounded-md bg-surface-muted p-3"><p className="text-sm font-semibold">{item.authorName}</p><p className="mt-1 text-sm text-text-muted">{item.body}</p></article>)}</div>{!['closed','declined'].includes(request.status) ? <form onSubmit={(event) => { event.preventDefault(); void sendReply(); }} className="mt-4"><textarea required value={reply} onChange={(event) => setReply(event.target.value)} className="min-h-24 w-full rounded-md border border-border px-3 py-2"/><button className="mt-3 rounded-md bg-brand px-3 py-2 text-sm font-semibold text-white">Send reply</button></form> : null}</section></main>;
}
