"use client";

import Link from 'next/link';
import { useState } from 'react';
import { setProjectAccessCode, updateProjectSharingSettings } from '@/lib/review-service';

export function ProjectSharingSettings({ projectId }: { projectId: string }) {
  const [code, setCode] = useState('');
  const [message, setMessage] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const [sharingEnabled, setSharingEnabled] = useState(true);
  const [allowRequests, setAllowRequests] = useState(true);
  const [allowReplies, setAllowReplies] = useState(true);
  const [allowReferences, setAllowReferences] = useState(true);
  const save = async () => { setSaving(true); setMessage(null); try { await setProjectAccessCode(projectId, code); setCode(''); setMessage(code.trim() ? 'Access code saved. Share it separately from the project link.' : 'Access code removed.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not update access code.'); } finally { setSaving(false); } };
  const savePermissions = async () => { setSaving(true); setMessage(null); try { await updateProjectSharingSettings(projectId, { sharingEnabled, allowClientRequests: allowRequests, allowClientRequestReplies: allowReplies, allowClientRequestReferences: allowReferences }); setMessage('Sharing controls saved.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not update sharing.'); } finally { setSaving(false); } };
  return <main className="min-h-screen bg-canvas px-4 py-6 text-text lg:px-8"><header className="border-b border-border pb-5"><Link href="/dashboard" className="text-sm font-semibold text-text-muted">← Projects</Link><p className="mt-4 text-xs font-semibold uppercase tracking-[0.2em] text-text-subtle">Project sharing</p><h1 className="mt-2 text-3xl font-semibold">Sharing controls</h1><p className="mt-2 max-w-xl text-sm leading-6 text-text-muted">Control what clients can access from the project link.</p></header><section className="mt-5 max-w-xl rounded-lg border border-border bg-surface p-4"><h2 className="font-semibold">Client access</h2><div className="mt-3 space-y-3 text-sm"><label className="flex gap-2"><input type="checkbox" checked={sharingEnabled} onChange={(event) => setSharingEnabled(event.target.checked)}/> Enable project link</label><label className="flex gap-2"><input type="checkbox" checked={allowRequests} onChange={(event) => setAllowRequests(event.target.checked)}/> Allow client Requests</label><label className="flex gap-2"><input type="checkbox" checked={allowReplies} onChange={(event) => setAllowReplies(event.target.checked)}/> Allow Request replies</label><label className="flex gap-2"><input type="checkbox" checked={allowReferences} onChange={(event) => setAllowReferences(event.target.checked)}/> Allow Request references</label></div><button disabled={saving} type="button" onClick={() => void savePermissions()} className="mt-4 rounded-md border border-border px-3 py-2 text-sm font-semibold disabled:opacity-50">Save sharing controls</button></section><section className="mt-5 max-w-xl rounded-lg border border-border bg-surface p-4"><h2 className="font-semibold">Access code</h2><form onSubmit={(event) => { event.preventDefault(); void save(); }} className="mt-3"><label className="block text-sm font-semibold">New access code<input type="password" minLength={6} value={code} onChange={(event) => setCode(event.target.value)} placeholder="Leave blank to remove protection" className="mt-2 w-full rounded-md border border-border px-3 py-2 font-normal" /></label><p className="mt-2 text-xs text-text-muted">Use at least six characters. The code is stored only as a secure hash.</p><button disabled={saving} className="mt-4 rounded-md bg-brand px-3 py-2 text-sm font-semibold text-white disabled:opacity-50">{saving ? 'Saving…' : 'Save access code'}</button></form>{message ? <p className="mt-3 text-sm text-text-muted" role="status">{message}</p> : null}</section></main>;
}
