"use client";
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { getProjectShareToken, listProjects, type ProjectSummary } from '@/lib/review-service';

export function ProjectDetail({ projectId }: { projectId: string }) {
  const [project, setProject] = useState<ProjectSummary | null | undefined>(undefined);
  const [shareMessage, setShareMessage] = useState<string | null>(null);
  useEffect(() => { void listProjects().then((items) => setProject(items.find((item) => item.id === projectId) ?? null)); }, [projectId]);
  if (project === undefined) return <main className="min-h-screen bg-canvas p-6 text-sm text-text-muted">Loading project…</main>;
  if (!project) return <main className="min-h-screen bg-canvas p-6 text-text"><h1 className="text-xl font-semibold">Project not found</h1><Link href="/projects" className="mt-4 inline-block text-sm font-semibold underline">Back to projects</Link></main>;
  const copyProjectLink = async () => { try { const shareToken = await getProjectShareToken(project.id); const link = `${window.location.origin}/project/${shareToken}`; await navigator.clipboard?.writeText(link); setProject((current) => current ? { ...current, shareToken } : current); setShareMessage('Project link copied. Only client-visible reviews appear there.'); } catch (error) { setShareMessage(error instanceof Error ? error.message : 'Could not prepare the project link.'); } };
  return <main className="min-h-screen bg-canvas px-4 py-6 text-text lg:px-8"><header className="flex flex-wrap items-start justify-between gap-3 border-b border-border pb-5"><div><Link href="/projects" className="text-sm font-semibold text-text-muted">← Projects</Link><h1 className="mt-3 text-3xl font-semibold">{project.name}</h1><p className="mt-2 text-sm text-text-muted">{project.client || 'No client'} · {project.reviews.length} reviews</p></div><div className="flex gap-2"><button type="button" onClick={() => void copyProjectLink()} className="rounded-md border border-border px-3 py-2 text-sm font-semibold">Share project</button><Link href={`/reviews/new?projectId=${project.id}`} className="rounded-md bg-brand px-3 py-2 text-sm font-semibold text-white">Add review</Link></div></header>{shareMessage ? <p className="mt-3 text-sm text-text-muted" role="status">{shareMessage}</p> : null}{project.description ? <p className="mt-5 max-w-2xl text-sm leading-6 text-text-muted">{project.description}</p> : null}<section className="mt-6 space-y-3">{project.reviews.length ? project.reviews.map((review) => <Link key={review.id} href={`/reviews/${review.id}`} className="flex items-center justify-between rounded-lg border border-border bg-surface p-4 hover:bg-surface-muted"><div><h2 className="font-semibold">{review.title}</h2><p className="mt-1 text-sm text-text-muted">{review.openComments} open comments · {review.latestActivityLabel}</p></div><span className="text-sm text-text-muted">{review.status}</span></Link>) : <p className="rounded-lg border border-dashed border-border p-6 text-sm text-text-muted">No reviews in this project yet.</p>}</section></main>;
}
